name: Test Schedule

on:
  schedule:
    # Run every 5 minutes for testing (more conservative)
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test scheduled workflow
        run: |
          echo "Scheduled workflow is working!"
          date